controller:
  extraArgs:
    "enable-ssl-passthrough": ""
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      scrapeInterval: 10s
      additionalLabels:
        # linking to prometheus instance
        release: "prometheus"
